name: Update Streams
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Unzip script
        run: |
          sudo apt-get install -y unzip
          unzip -P ${{ secrets.ZIP_PASS }} vps_server.zip

      - name: Run script
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: node vps_server.js


